### ISSUE TITLE
Restore previous behavior which preserved the prompt after a oneshot rlwrap

### ISSUE THREAD

**Issue by olejorgenb** [hanslub42/rlwrap#138] opened 2021-10-09 19:46 UTC
```
LINE=$(rlwrap -S "> " -o -- cat)
```
Would previously leave "> whatever was typed" in the terminal. Now the prompt is erased but the typed input is still preserved.

Is it possible to bring the old behavior back? I've tried writing the prompt manually, but seems hard to get it on the same line.

**Comment by hanslub42** [comment] 2021-10-10 12:03
This is very probably a duplicate of bug #108. If this is indeed the case, you can either:

- upgrade to `rlwrap-0.44` or newer 
- add the following lines to your `.inputrc`:
```
$if cat
     set enable-bracketed-paste off
$endif
```    
 Closing for now, but will re-open if the above  doesn't help.

**Closed by hanslub42** 2021-10-10 12:03 UTC
