### ISSUE TITLE
rlwrap43 erases prompts

### ISSUE THREAD

**Issue by ericjunkermann** [hanslub42/rlwrap#109] opened 2021-01-11 16:01 UTC
Without rlwrap, my program does this:

    % xxxx
    invalid command name "xxxx"
    %

With rlwrap, I get the prompt, but when I press return, my screen shows:

    xxxx
    invalid command name "xxxx"
    %

i.e.  the prompt vanishes. This makes it impossible for me to look back up my screen and distinguish input from output.

This happens with a number of totally unrelated programs.

    $ rlwrap --version
    rlwrap 0.43
    $ ldd `which rlwrap`
            linux-vdso.so.1 (0x00007ffc4028c000)
            libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fc826cae000)
            libreadline.so.8 => /usr/lib/libreadline.so.8 (0x00007fc826c59000)
            libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fc826be7000)
            libc.so.6 => /usr/lib/libc.so.6 (0x00007fc826a23000)
           /lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc826cdc000)`

    # uname -a
    Linux bruno 5.9.14_1 #1 SMP 1607957763 x86_64 GNU/Linux

This is on Void Linux.

**Comment by hanslub42** [comment] 2021-01-11 17:58
This is a duplicate of #108. Closing.

**Closed by hanslub42** 2021-01-11 17:58 UTC

**Comment by hanslub42** [comment] 2021-01-11 18:26
Anyways, thanks for the report! The easiest way to mitogate this problem (until `rlwrap-0.44` comes out) is do add a line

    set enable-bracketed-paste off 

to your  `~/.inputrc`

**Comment by ericjunkermann** [comment] 2021-01-12 13:01
Thanks. Sorry I missed noticing #108.
