### ISSUE TITLE
redirected rlwrap does not leave terminal in original state

### ISSUE THREAD

**Issue by haji-ali** [hanslub42/rlwrap#145] opened 2021-12-14 07:53 UTC
If I try this example in bash on `rlwrap 0.43`

```
reply=$(rlwrap -S 'Do you want to continue? ' -f <(echo "Yes No Maybe") -o cat)
```

but then abort (with Ctrl-C) instead of inputting anything, my bash prompt gets broken (I cannot enter any input). 
Any subsequent calls to rlwrap also put me in an infinite loop.

Is this expected? How do I fix it?

My bash is
```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by hanslub42** [comment] 2021-12-14 10:04
I cannot reproduce this, for me your example works without any problems. What happens if you enter the following command in `bash`:

     rlwrap -S 'Do you want to continue? ' -f <(echo "Yes No Maybe") -o cat

... and then press `Ctrl-C`?

**Comment by haji-ali** [comment] 2021-12-14 10:18
This works as expected. It's only when I assign to a variable that I observe those problems.
Strangely, I also just tried on a different machine with an older bash and could not reproduce it.

I am not 100% sure how to troubleshoot this issue, please let me know if you have any ideas. Meanwhile, I will try to install an older bash and report back.

**Comment by haji-ali** [comment] 2021-12-15 13:50
Just compiled bash from here
https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz

using 
```
curl https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz | tar zxf -
cd bash-5.0
./configure && make && ./bash
```

Then tried the command above
```
bash-5.0$ reply=$(rlwrap -S 'Do you want to continue? ' -f <(echo "Yes No Maybe") -o cat)
```
and hit `Ctrl-C` immediately and was able to reproduce the problem.

@hanslub42, can you reproduce the problem this way?

**Comment by hanslub42** [comment] 2021-12-16 15:57
The problem already appears with a simple:

    reply=$(rlwrap cat)

`rlwrap` remembers the terminal settings at startup and always restores them when exiting (even after a `SIGINT`). I can verify that this happens in the above case as well, and that those terminal settings have the `ECHO` bit set (as expected). That means that is must be `bash` that clears the `ECHO` bit after `rlwrap`s death.


ALl this makes me doubt that there is much I can do to prevent your problem from occurring. The fact that it doesn't happen with the newest `bash` only reinforces this doubt.

**Comment by haji-ali** [comment] 2021-12-16 17:29
Yes, I also came to the same realization. I ended up trapping `SIGINT` in my script that calls `rlwrap` and restoring the stty settings which fixes the issue for my particular case on bash 5.0.

Since this bug seems more relevant to bash 5.0 than to `rlwrap`, I will close the issue. Thank you for checking.

**Comment by hanslub42** [comment] 2022-05-12 10:24
I suddenly realise that `rlwrap` should restore the terminal settings by manipulating the tty that is connected to `stdin` (currently it works on `stdout`). Usually, both are connected to the same tty, but not in cases where `rlwrap`s output is redirected, as in the question above. Duh!

Reopening....

**Comment by hanslub42** [comment] 2022-10-20 09:50
> I suddenly realise that rlwrap should restore the terminal settings by manipulating the tty that is connected to stdin (currently it works on stdout). Usually, both are connected to the same tty, but not in cases where rlwraps output is redirected, as in the question above. Duh!

This is not true, my mistake The manual states:

>  When stdout (or stderr) is not a terminal,  rlwrap  will re-open it to /dev/tty (the users terminal) after it has started command, so that command's output is redirected as expected, but keyboard input and rlwrap error messages are still visible

So even though `rlwrap` restores the terminal settings by manipulating `stdout`, this will always be connected to the users teminal

Morover, I can reproduce the problem with `bash` 5.0, but not with `bash` 5.1 anymore. Conclusion: this was not a `rlwrap` problem after all. Closing

**Closed by hanslub42** 2022-10-20 09:50 UTC
Labels: bug
