### ISSUE TITLE
Permission denied if .sqlplus_history does not exist

### ISSUE THREAD

**Issue by Vi1i** [hanslub42/rlwrap#90] opened 2018-09-20 12:39 UTC
After installing `rlwrap` from the Arch Linux repo with `yay`, if the `.sqlplus_history` file does not exists I get:
`rlwrap: error: cannot create history file /home/REDACTED/.sqlplus_history: Permission denied`

Executing `rlwrap --history-filename=$HOME/.${USER}_command_history` gives the same error.
As I install this in our university labs for database classes, I have told the students to execute `touch ~/.sqlplus_history` which allows them to use the command and maintain the history.

Any help would be appreciated, if needed I can fork and look for the issue.

**Comment by Michael-Cook-Bose** [comment] 2018-09-20 12:46
That means either you don't have permission to create files in `/home/REDACTED` or else the file .sqlplus_history already exists but you don't have permission to write to it.

You'll likely see the same permission denied error if you do `cp /dev/null /home/REDACTED/.sqlplus_history`.

Perhaps you don't own `/home/REDACTED` or (if it exists) `.sqlplus_history`.
Or if you do own them, perhaps you need to `chmod +w` them.

I'm assuming rlwrap is running as you.

**Comment by Vi1i** [comment] 2018-09-20 13:34
I have full permission on the /home/REDACTED directory, it is my home directory. All other applications are running fine, as `touch /homeREDACTED/.sqlplus_history` works with no problem.
I can copy `/dev/null` without issues. The only application running into this is `rlwrap`.

I execute `rlwrap sqlplus`, how can I verify the user it is running as?

**Comment by Michael-Cook-Bose** [comment] 2018-09-20 14:16
`ps` will tell you.

Did you try invoking sqlplus directly (not `rlwrap sqlplus` but just `sqlplus`)?
I suspect you'll find this issue happens without rlwrap (i.e., it doesn't have anything to do with rlwrap).

**Comment by Vi1i** [comment] 2018-09-20 14:47
Invoking `sqlplus` causes no issues, and works correctly.
As I can't catch it when it has the error, the error happens immediately, I checked the process when I `touch ~/.sqlplus_history`. It showed that it runs as my user when executing.
```bash
REDACTED_USER 24171 23267  0 10:36 pts/0    00:00:00 rlwrap sqlplus
drwxr-xr-x  1 /home/REDACTED_USER              users 3.0K Sep 20 10:41 REDACTED_USER
```

```bash
[REDACTED_USER@arch01 ~]$ strace rlwrap sqlplus
execve("/usr/bin/rlwrap", ["rlwrap", "sqlplus"], 0x7ffc37ad6f38 /* 25 vars */) = 0
brk(NULL)                               = 0x111d000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffe5c94aa40) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=226482, ...}) = 0
mmap(NULL, 226482, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f72fc7f4000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \20\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14232, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f72fc7f2000
mmap(NULL, 16400, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f72fc7ed000
mmap(0x7f72fc7ee000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f72fc7ee000
mmap(0x7f72fc7ef000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f72fc7ef000
mmap(0x7f72fc7f0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f72fc7f0000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libreadline.so.7", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0pU\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=359664, ...}) = 0
mmap(NULL, 2410728, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f72fc5a0000
mprotect(0x7f72fc5e3000, 2097152, PROT_NONE) = 0
mmap(0x7f72fc7e3000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x43000) = 0x7f72fc7e3000
mmap(0x7f72fc7ec000, 2280, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f72fc7ec000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260`\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=457800, ...}) = 0
mmap(NULL, 2542936, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f72fc333000
mprotect(0x7f72fc39b000, 2093056, PROT_NONE) = 0
mmap(0x7f72fc59a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x67000) = 0x7f72fc59a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000C\2\0\0\0\0\0"..., 832) = 832
lseek(3, 792, SEEK_SET)                 = 792
read(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\210o7\21\1\307=\311\366\263\256\202p\3777\335"..., 68) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=2136840, ...}) = 0
lseek(3, 792, SEEK_SET)                 = 792
read(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\210o7\21\1\307=\311\366\263\256\202p\3777\335"..., 68) = 68
lseek(3, 864, SEEK_SET)                 = 864
read(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 1848896, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f72fc16f000
mprotect(0x7f72fc191000, 1671168, PROT_NONE) = 0
mmap(0x7f72fc191000, 1355776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f72fc191000
mmap(0x7f72fc2dc000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16d000) = 0x7f72fc2dc000
mmap(0x7f72fc329000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b9000) = 0x7f72fc329000
mmap(0x7f72fc32f000, 13888, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f72fc32f000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f72fc16d000
arch_prctl(ARCH_SET_FS, 0x7f72fc16db80) = 0
mprotect(0x7f72fc329000, 16384, PROT_READ) = 0
mprotect(0x7f72fc59a000, 20480, PROT_READ) = 0
mprotect(0x7f72fc7e3000, 12288, PROT_READ) = 0
mprotect(0x7f72fc7f0000, 4096, PROT_READ) = 0
mprotect(0x613000, 4096, PROT_READ)     = 0
mprotect(0x7f72fc855000, 4096, PROT_READ) = 0
munmap(0x7f72fc7f4000, 226482)          = 0
brk(NULL)                               = 0x111d000
brk(0x113e000)                          = 0x113e000
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=66, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
stat("/home/REDACTED_USER/.terminfo", 0x111dd80) = -1 ENOENT (No such file or directory)
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
access("/usr/share/terminfo/v/vt100", R_OK) = 0
openat(AT_FDCWD, "/usr/share/terminfo/v/vt100", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1190, ...}) = 0
read(3, "\32\1,\0&\0\7\0\16\1\36\2vt100|vt100-am|dec v"..., 32768) = 1190
read(3, "", 28672)                      = 0
close(3)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=66, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
access("/usr/share/terminfo/x/xterm-color", R_OK) = 0
openat(AT_FDCWD, "/usr/share/terminfo/x/xterm-color", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1551, ...}) = 0
read(3, "\32\1'\0&\0\20\0\235\1[\2xterm-color|nxterm|g"..., 32768) = 1551
read(3, "", 28672)                      = 0
close(3)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=66, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
access("/usr/share/terminfo/x/xterm-color", R_OK) = 0
openat(AT_FDCWD, "/usr/share/terminfo/x/xterm-color", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1551, ...}) = 0
read(3, "\32\1'\0&\0\20\0\235\1[\2xterm-color|nxterm|g"..., 32768) = 1551
read(3, "", 28672)                      = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=66, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
access("/home/REDACTED_USER/.sqlplus_history", F_OK) = -1 ENOENT (No such file or directory)
access("/home/REDACTED_USER", W_OK)          = -1 EACCES (Permission denied)
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(2, "rlwrap: error: cannot create his"..., 93rlwrap: error: cannot create history file /home/REDACTED_USER/.sqlplus_history: Permission denied
) = 93
rt_sigprocmask(SIG_UNBLOCK, ~[RTMIN RT_1], NULL, 8) = 0
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=10000}) = 0 (Timeout)
ioctl(0, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0
exit_group(1)                           = ?
+++ exited with 1 +++

```

**Comment by Michael-Cook-Bose** [comment] 2018-09-20 14:56
This line shows that the .sqlplus_history file doesn't already exist:
```
access("/home/REDACTED_USER/.sqlplus_history", F_OK) = -1 ENOENT (No such file or directory)
```

This line shows that rlwrap doesn't have permission to create files in the REDACTED_USER directory:
```
access("/home/REDACTED_USER", W_OK)          = -1 EACCES (Permission denied)
```

What do these commands output:
```
$ id
$ rlwrap --history-filename /tmp/foo id
$ ls -lL `which rlwrap`
```

**Comment by Vi1i** [comment] 2018-09-20 15:49
```bash
[REDACTED_USER@arch01 ~]$ id
uid=8102(REDACTED_USER) gid=1001(users) groups=1001(users),150(wireshark),1003(staff),1004(dba)
[REDACTED_USER@arch01 ~]$ rlwrap --history-filename /tmp/foo id
uid=8102(REDACTED_USER) gid=1001(users) groups=1001(users),150(wireshark),1003(staff),1004(dba)
[REDACTED_USER@arch01 ~]$ ls -lL `which rlwrap`
-rwxr-xr-x 1 root root 86760 May 23  2017 /usr/bin/rlwrap
```

**Comment by Michael-Cook-Bose** [comment] 2018-09-20 15:55
How about `ls -ld /home/REDACTED_USER`

**Comment by Vi1i** [comment] 2018-09-20 17:31
```bash
drwxr-xr-x 1 REDACTED_USER users 3040 Sep 20  2018 /home/REDACTED_USER
```

**Comment by Michael-Cook-Bose** [comment] 2018-09-20 18:02
Everything looks right, like it should work.
Your home directory is owned by you, it's writeable by you, the .sqlplus_history does not exist, rlwrap is not setuid.

What if you do `rm -f /tmp/foo; rlwrap --history-filename /tmp/foo sqlplus` then `ls -l /tmp/foo`

**Comment by Vi1i** [comment] 2018-09-24 18:33
Sorry for the wait:
`-rw------- 1 REDACTED_USER users 19 Sep 24 14:31 /tmp/foo`

**Comment by Vi1i** [comment] 2018-09-24 19:57
Sorry for the wait:
`-rw------- 1 REDACTED_USER users 19 Sep 24 14:31 /tmp/foo`

**Comment by hanslub42** [comment] 2018-10-09 22:06
What does `ls -ld /home` say?

**Comment by fweimer** [comment] 2018-10-11 11:49
@Vi1i Have you enabled AppArmor or some other security technology? Is there anything in the system audit log which looks relevant?

**Comment by Vi1i** [comment] 2018-10-15 17:06
@hanslub42 `drwxr-xr-x 1 root users 34024 Sep 13 09:59 /home`
@fweimer AppArmor and other technologies are off, no audit logs or other logs showing anything.

**Comment by hanslub42** [comment] 2018-10-15 21:54
It might be irrelevant, but I'm a bit surprised by the `1` in column 2 of your `ls -ld` output. On most file systems even an _empty_ directory will have at least `2`, full directories like `/home` will have a lot more. 

So, on what filesystem does your `/home` live? (can be seen with e.g. `df -T /home`).  On some filesystems the `access()`  misbehaves. From the `access (2)` manpage:

>These calls may not work correctly on NFSv2 filesystems with UID mapping enabled, because UID  mapping is done on the  server  and  hidden  from  the  client, which checks permissions.  (NFS versions 3 and higher perform the check on the server.)  Similar problems can occur to        FUSE mounts

**Comment by Vi1i** [comment] 2018-10-16 13:52
Yes, the home mounts are on NFSv3. With that said, I am sorry I didn't think to include it originally.
```bash
Filesystem                            Type  1K-blocks       Used  Available Use% Mounted on
fileserv.REDACTEDDOMAIN:/volume1/homes/ nfs  9851112192 4177698304 5673413888  43% /home
```

**Comment by hanslub42** [comment] 2018-10-17 15:57
OK, my guess is that the NFS mounted directory itself lives on `btrfs` (this would explain the link count `1` on all directories). Not the most usual setup maybe, but it should definitely work OK.

A few questions:

- What (if anything) does ` env test -w  $HOME  || echo "$HOME not writable by $USER"` print if executed by an ordinary user (the gnu coreutils `test` (or `[`) command uses `access (2)` to determine writability)
-  are you willing to share the mount options and the relevant line in `/etc/exports` on the NFS server? I would like to try and replicate the problem (although I'm not sure it is a `rlwrap` bug to begin with)

If all else fails you could  write a little wrapper script that `touch`es any not yet existing history file before executing `rlwrap`

**Comment by Vi1i** [comment] 2018-10-29 18:07
```bash
[REDACTED_USER@appserv ~]$ env test -w $HOME || echo "$HOME not writable by $USER"
/home/REDACTED_USER not writable by REDACTED_USER
```

```bash
REDACTED_IP:/volume1/homes/           /home   nfs     _netdev,auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemdidle-timeout=1min 0
```

**Comment by hanslub42** [comment] 2021-01-10 13:41
Cannot reproduce. Closing.

**Closed by hanslub42** 2021-01-10 13:41 UTC
