### ISSUE TITLE
rlwrap options to work with matlab

### ISSUE THREAD

**Issue by sebma** [hanslub42/rlwrap#74] opened 2017-06-01 16:10 UTC
Hi,

I'm trying to make rlwrap work with matlab on MacOS, here is the command I type : 

`$ rlwrap -c -m " \ " -H "$MATLAB/history.m" matlab -nodesktop -nosplash`

Alt+left, Alt+right, Esc+Backspace,Ctrl+D and Ctrl+R keyboard shortcuts don't work, can you help me ?

**Comment by hanslub42** [comment] 2017-06-02 07:27
In most cases where `rlwrap` doesn't seem to do anything at all one needs to add the `--always-readline` (`-a`) option. 

    $ rlwrap -a -c -m " \ " -H "$MATLAB/history.m" matlab -nodesktop -nosplash
 
This should work, but then, if the rlwrapped program ever asks for single keypresses, like in:  `really burn your house? Y/N` you will have to always follow them with <kbd>ENTER</kbd>, which quickly becomes annoying.

Therfore, it is often better to get the rlwrapped program to not do any line editing, and to omit the `-a` option.  With `node`, for example, one can do:

    $ NODE_NO_READLINE=1 rlwrap node

I don't know whether `matlab` has a similar option or environment variable.

**Comment by sebma** [comment] 2017-06-02 11:40
First, on MacOS, you have to give an argument for each option otherwise `-a -c` will be interpreted as `-a=c`

What option can I give to `-a` ?

Second, if rlwrap does not do the line editing, what else do I need it for ?

**Comment by hanslub42** [comment] 2017-06-02 12:21
> What option can I give to -a ?

Anything will do, but use something that is not likely to ever show up as a prompt

    rlwrap -a xxxxx -c -m " \ " -H "$MATLAB/history.m" matlab -nodesktop -nosplash
 

> Second, if rlwrap does not do the line editing, what else do I need it for ?

I wrote: "Therefore, it is often better to get the _rlwrapped_ program to not do any line editing". The rlwrapped program is `matlab`, not `rlwrap` itself. So `rlwrap` is doing the line editing, while `matlab` is not doing any.

**Comment by sebma** [comment] 2017-06-02 12:29
You're right, I misunderstood the second part, sorry.

On Linux, what is the default argument set by your rlwrap binary for the `-a` option ?
Maybe I can use the same argument on MacOS.

**Comment by hanslub42** [comment] 2017-06-02 12:35
> On Linux, what is the default argument set by your rlwrap binary for the -a option ?

There is none. (internally, `rlwrap` will use the NULL pointer to signal that `-a` didn't have an argument, but you cannot give that as an argument). I would use a nonsense string like `dusynqwue7sid`

**Comment by sebma** [comment] 2017-06-02 12:42
How about an empty string, like this : `-a ""` ?

**Comment by sebma** [comment] 2017-06-02 12:45
It does not seem to work with an empty string :(

Trying with a nonsense string ...

**Comment by sebma** [comment] 2017-06-02 12:51
Everything works with : `-a any`, except `Ctrl+D`

Do you have any idea why `Ctrl+D` does not work ?

**Comment by hanslub42** [comment] 2017-06-02 12:59
> Do you have any idea why Ctrl+D does not work ?

No. It happens sometimes (usually on non-glibc systems) but I never have looked into it.

Can you run rlwrap with the --debug option? If not, can you compile it yourself?

If so, you could help me with 

    $ rlwrap --debug -a xxxxx -c -m " \ " -H "$MATLAB/history.m" matlab -nodesktop -nosplash
    
and then sending me the resulting `/tmp/rlwrap.debug`

**Comment by sebma** [comment] 2017-06-02 13:30
I need to rebuild it

**Comment by sebma** [comment] 2017-06-02 13:38
Having issues configuring : 

```
configure: checking for pty ranges...
checking for tgetent... no
checking for tgetent in -ltinfo... no
checking for tgetent in -lcurses... yes
checking for readline in -lreadline... yes
checking for tigetnum... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking whether your readline headers and library know about rl_set_screen_size... yes
checking whether your readline headers and library know about rl_basic_quote_characters... no
configure: error:

********************************************************************************
The readline library that I found is incomplete, probably just a wrapper
around libedit (like on Mac OS X) Please install GNU Readline and re-configure
with the correct CFLAGS and LDFLAGS (cf. the instructions in INSTALL)
********************************************************************************

```

**Comment by sebma** [comment] 2017-06-02 13:51
Here is my configure command, can you help ?

`$ ./configure --prefix=/usr/local --exec-prefix=/usr/local CFLAGS=-I/usr/local/include CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib --enable-debug`

**Comment by hanslub42** [comment] 2017-06-03 07:18
Your configure command looks OK, _provided_ you have the real (GNU) `readline` installed under /usr/local. In OS X, the default readline library is (for copyright reasons) only an incomplete _emulation_ of GNU readline (actually a thin wrapper around editline)

If you manage to install GNU readline (maybe using `brew`) you should substitute its location for the `/usr/local` in your configure command, so that it can pick up the right readline library.

**Comment by sebma** [comment] 2017-06-03 10:46
I already installed readline using `brew` : 
```
$ brew list | grep readline
readline
```
Next Tuesday (this comming Monday is off), I'll check it's location to see if brew installed it in /usr/local

**Comment by sebma** [comment] 2017-06-06 12:27
Hi, I had to do this with brew : 
```
$ brew link -v --force readline
Linking /usr/local/Cellar/readline/7.0.3_1...
ln -s ../Cellar/readline/7.0.3_1/include/readline readline
ln -s ../../Cellar/readline/7.0.3_1/share/doc/readline readline
ln -s ../../Cellar/readline/7.0.3_1/share/info/history.info history.info
info /usr/local/share/info/history.info
ln -s ../../Cellar/readline/7.0.3_1/share/info/readline.info readline.info
info /usr/local/share/info/readline.info
ln -s ../../Cellar/readline/7.0.3_1/share/info/rluserman.info rluserman.info
info /usr/local/share/info/rluserman.info
ln -s ../../../Cellar/readline/7.0.3_1/share/man/man3/history.3 history.3
ln -s ../../../Cellar/readline/7.0.3_1/share/man/man3/readline.3 readline.3
ln -s ../Cellar/readline/7.0.3_1/share/readline readline
ln -s ../Cellar/readline/7.0.3_1/lib/libhistory.7.0.dylib libhistory.7.0.dylib
ln -s ../Cellar/readline/7.0.3_1/lib/libhistory.7.dylib libhistory.7.dylib
ln -s ../Cellar/readline/7.0.3_1/lib/libhistory.a libhistory.a
ln -s ../Cellar/readline/7.0.3_1/lib/libhistory.dylib libhistory.dylib
ln -s ../Cellar/readline/7.0.3_1/lib/libreadline.7.0.dylib libreadline.7.0.dylib
ln -s ../Cellar/readline/7.0.3_1/lib/libreadline.7.dylib libreadline.7.dylib
ln -s ../Cellar/readline/7.0.3_1/lib/libreadline.a libreadline.a
ln -s ../Cellar/readline/7.0.3_1/lib/libreadline.dylib libreadline.dylib
16 symlinks created
```

The configuration and build worked :)

**Comment by sebma** [comment] 2017-06-06 12:35
Here is the [rlwrap.debug](http://sprunge.us/EKGV)

**Comment by sebma** [comment] 2017-06-06 12:36
BTW: Matlab completion does not work.
That is the most annoying, actually.

**Comment by hanslub42** [comment] 2017-06-06 13:28
Thanks for the debug file. `rlwrap` indeed loses the original Matlab completion. There are ways to get this completion back, cf the StackOverflow question [A node shell based on gnu readline](https://stackoverflow.com/questions/43505223/a-node-shell-based-on-gnu-readline/43677273#43677273)

**Comment by hanslub42** [comment] 2021-01-01 16:57
The only unsolved issue in this exchange is `CTRL+D` not working, which I cannot reproduce right now. Closing.

**Closed** 2021-01-10 13:41 UTC
Labels: question
