### ISSUE TITLE
Right-shifted input (or double prompt) after accepting a line in bracketed-paste-mode with readline-8.2 

### ISSUE THREAD

**Issue by ok2** [hanslub42/rlwrap#168] opened 2022-11-01 19:14 UTC
When I use `rlwrap` with a command, which has a prompt, then I get very strange behaviour, when I type this:
```
$> rlwrap /bin/ed -p'* '
* q
```
typing `q` and then press "Enter key":

```
$> rlwrap /bin/ed -p'* '
* * q

```
It changes the line with the prompt to `* * q`. When I use a different prompt:
```
$> rlwrap /bin/ed -p'testprompt> '
testprompt> testprompt> q

```

I mean it works, but this prompt copy is disturbing. When I use `with-readline` instead `rlwrap` it does not happen. It also happens just on my Mac OS X 13.0, not on Linux. Apple silicon and Intel-based behave slightly differently but have a similar error. On Intel it looks like that after entering `q` and pressing enter (instead of prompt, it copies the command):
```
$> rlwrap /bin/ed -p '* '
* q q

❯ rlwrap /bin/ed -p 'testprompt> '
testprompt> q           q

```

I have `rlwrap 0.46` (from `brew` or compiled manually makes no difference)

Does anybody have an idea what could be wrong?

**Comment by frou** [comment] 2022-11-03 07:55
On macOS 12 (Monterey) with Terminal/iTerm, I still experience the #166 bug ("rlwrap rewrites the input line right-shifted") even though I'm running rlwrap 0.46. So things definitely seem to be dodgy on the macOS front at the moment.

**Comment by hanslub42** [comment] 2022-11-03 08:34
What readline version do you use? And does putting 

     set enable-bracketed-paste off

... into your `.inputrc` change anything?

**Comment by frou** [comment] 2022-11-03 09:21
I think you're asking the OP, but if you'll excuse me I'll answer anyway:

> What `readline` version do you use?

readline installed as a dependency of rlwrap by `brew` and it's version 8.2.1

> And does putting `set enable-bracketed-paste off` into your `.inputrc` change anything?

Yes, that stops the thing I'm seeing from happening. I remember having to apply that workaround in the past for #108, but I removed it after rlwrap 0.44 was released with a fix.

**Comment by hanslub42** [comment] 2022-11-03 10:17
Can (one of) you recompile with debugging enabled (`autoreconf`, `./configure --enable-debug`, `make`) 

then

     src/rlwrap --debug /bin/ed -p 'testprompt> '

...type <kbd>q</kbd> <kbd>ENTER</kbd>, and then send me (hanslub42@gmail.com) the resulting `/tmp/rlwrap.debug`?

**Comment by ok2** [comment] 2022-11-05 10:58
Now with debug. How I typed:
```
$> ./src/rlwrap --debug /bin/ed -p 'testprompt> '
testprompt> q
```

How it looked like after typing `ENTER`:
```
$> ./src/rlwrap --debug /bin/ed -p 'testprompt> '
testprompt>             q
```

[rlwrap.debug.txt](https://github.com/hanslub42/rlwrap/files/9943598/rlwrap.debug.txt)

**Comment by hanslub42** [comment] 2022-11-05 12:17
Comparing your debug file with mine, I don't see any (relevant) differences. Still, your terminal gets messed up and mine doesn't

Could you check out and compile branch `bug-168-prompt-handling-on-OSX`, or just comment out/remove two lines 313-314 in `readline.c`:

     if (bracketed_paste_enabled)
          my_putstr(term_enable_bracketed_paste);
          
It might be the case that outputting `term_enable_bracketed_paste` (`"\033[?2004h"`) at that point confuses  some terminals

If my hunch is right, the bug can also be avoided on OSX by using a terminal like `rxvt` of `xterm` (if you happen to have an X server  lying around somewhere....)

**Comment by ok2** [comment] 2022-11-05 12:23
The `bug-168-prompt-handling-on-OSX` does not change anything here, also commenting out the two lines do not change anything either:
```
$> ./src/rlwrap --debug /bin/ed -p 'testprompt> '
testprompt>             q
```

[rlwrap.debug.txt](https://github.com/hanslub42/rlwrap/files/9943771/rlwrap.debug.txt)
[rlwrap.debug.txt](https://github.com/hanslub42/rlwrap/files/9943776/rlwrap.debug.txt)

**Comment by ok2** [comment] 2022-11-05 12:46
Maybe interesting enough, neither `xterm` (version 375 on xquartz 2.8.2) nor `rxvt` changes anything.

[rlwrap.debug.txt](https://github.com/hanslub42/rlwrap/files/9943817/rlwrap.debug.txt)

**Comment by hanslub42** [comment] 2022-11-05 13:18
There is an undocumented debug option that slows down and shows cursor movement. 

When I run

     ./src/rlwrap --debug=4096  /bin/ed -p 'testprompt> '
     
and then press q <kbd>ENTER</kbd>

I see:

    1estprompt> q
    2
    testprompt> 3
    
 I suspect that the function `move_cursor_to_start_of_prompt()` doesn't do what its name suggests and you will see something like 
 
    testprompt> 1

(The relevant code is at `readline.c:243`)

Can you try this out for me?

**Comment by ok2** [comment] 2022-11-05 13:46
Yes, sure, I have recorded a video how it looks like because it is not easy to explain 😄 

https://user-images.githubusercontent.com/201152/200122968-61db047b-edfa-4346-833c-969ca75b09b7.mov

**Comment by ok2** [comment] 2022-11-05 15:35
By the way, writing `set enable-bracketed-paste off` to `~/.inputrc` fixes this problem. I am not sure why bracketed paste mode influences the prompt.

**Comment by hanslub42** [comment] 2022-11-05 17:14
See #108. It turned out that in bracketed-paste mode, `rl_redisplay()` would not display the prompt, and the prompt would disappear after entering a line.  That is why I added [some code](https://github.com/hanslub42/rlwrap/blob/3282c9dac19aa7fa01206d4aff6f518e5f9bf2e0/src/readline.c#L243) to print the prompt before calling `rl_redisplay()`

However, it now turns out that _on some systems_ the prompt gets reprinted by `rl_redisplay()` after all, and we end  with _two_ prompts (or the prompt and spaces, when called with `--debug`, which might provide a clue.

I will have to delve in the `readline` source code to get  to the bottom of this.

**Comment by hanslub42** [comment] 2022-11-05 17:33
obfusk's comment in #108 maybe provides a clue:

> - when bracketed-paste is enabled, `rl_deprep_terminal()` prints `BRACK_PASTE_FINI` (`"\033[?2004l\r"`) to `rl_outstream`;
> - this moves the cursor to the beginning of the line (instead of the position after the prompt), which causes the `rlwrap` prompt to be overwritten during `rl_redisplay()`.

The current problem (especially the fact that `rlwrap` is outputting _exaclty_ the same bytes in both buggy and non-buggy scenarios) would be explained if  `BRACK_PASTE_FINI`  would *not* move the cursor. on some terminals, even though it is difficult to imagine that this would happen on OSX `xterm` and not on linux `xterm`.

But, as Sherlock Holmes said: _When you have eliminated the impossible, whatever remains, however improbable, must be the truth._

I'll try and extend the terminal testing code at the end ot `term.c` to make it possible to tes

**Comment by hanslub42** [comment] 2022-11-05 17:57
STOP PRESS: It turns out that I _can_ reproduce this, after all, with readline-8.2 

Even though I had compiled `rlwrap` with `readline-8.2` it still picked up the system-wide shared library for `readline-8.1` 

This is not OSX-specific after all, but rather dependent on the `readline` version, so I changed the bug title accordingly.

**Comment by hanslub42** [comment] 2022-11-05 19:06
> The current problem [...] would be explained if  `BRACK_PASTE_FINI`  would *not* move the cursor. on some terminals, or `readline` doesnt output it

`BRACK_PASTE_FINI` ends with `CR` so it will always move the cursor, and `readline-8.2` still outputs is

But now `readline` realises that it moves the cursor. From `readline`s `rltty.c`:

```c
if (terminal_prepped & TPX_BRACKPASTE)
{
  fprintf (rl_outstream, BRACK_PASTE_FINI);
  /* Since the last character in BRACK_PASTE_FINI is \r */
  _rl_last_c_pos = 0;
```

Those last two lines are not found in `readline-8.1` but were added in `8.2`

**Comment by hanslub42** [comment] 2022-11-05 21:54
This should now be fixed in branch `bug-168-prompt-handling-on-OSX`. Can you confirm?

I essentially reverted the changes I made for #108 as `readline-8.2` doesn't need those anymore. 
This means that `rlwrap`, when compiled with pre-8.2 1readline` will no longer  honour `set enable-bracketed-paste on`

People who want to use `rlwrap` with older `readline` and still have bracketed paste work should stay on `rlwrap-0.44` or earlier.

**Comment by hanslub42** [comment] 2022-11-06 10:02
merged `bug-168-prompt-handling-on-OSX` and released `0.46.1`. Closing

**Closed** 2022-11-06 10:12 UTC
Labels: bug

**Comment by frou** [comment] 2022-11-06 10:33
Thank you very much Hans. For the record I've submitted 0.46.1 to Homebrew in https://github.com/Homebrew/homebrew-core/pull/114905

**Comment by ok2** [comment] 2022-11-06 19:20
It works fine for me, thank you very much! 👍
